# -*- coding: utf-8 -*-
"""Untitled32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/143QiAYcef_QiGOvciuBnypi0T2HJmlD6
"""

import os
import sys

# --- AUTO-INSTALLER ---
try:
    import numpy as np
    import pandas as pd
    import skfuzzy as fuzz
except ImportError:
    print("Installing required libraries... please wait.")
    os.system(f"{sys.executable} -m pip install numpy pandas scikit-fuzzy")
    import numpy as np
    import pandas as pd
    import skfuzzy as fuzz

# ==========================================
# VLIF MODEL (INTEGRASI VPD + IBK/LVI)
# ==========================================
class VLIFModelSumatra:
    def __init__(self, m=2.0, epsilon=1e-5, max_iter=1000):
        self.m = m
        self.epsilon = epsilon
        self.max_iter = max_iter
        self.centroids = None

    def calculate_flfi(self, temp, rh, soil_m, peat, lvi_score):
        # 1. Atmospheric Component (VPD)
        es = 0.61078 * np.exp((17.27 * temp) / (temp + 237.3))
        vpd = es - (es * (rh / 100))

        # 2. Edaphic Component (IBK / Land Vulnerability)
        # Sesuai logika: Kelembapan tanah vs Beban Gambut & Tutupan
        ibk_raw = soil_m - ((peat * 0.7) + (lvi_score * 0.3))

        # 3. Integration into FLFI (Index Risiko)
        # Karena IBK rendah = risiko tinggi, kita gunakan (1 - IBK)
        flfi = (vpd + (1 - ibk_raw)) / 2
        return flfi

    def run_ufcm(self, data):
        X = data.reshape(1, -1)
        cntr, u, u0, d, jm, p, fpc = fuzz.cluster.cmeans(
            X, c=3, m=self.m, error=self.epsilon,
            maxiter=self.max_iter, init=None
        )
        # Sorting Cluster agar 0=Aman, 1=Waspada, 2=Awas
        idx = np.argsort(cntr.flatten())
        self.centroids = cntr[idx]
        return np.argmax(u[idx], axis=0)

    def validate_er(self, df, label_col, hotspot_col):
        total_h = df[hotspot_col].sum()
        total_n = len(df)
        results = []
        labels = {0: 'Aman (Low)', 1: 'Waspada (Mod)', 2: 'Awas (High)'}

        for i in range(3):
            subset = df[df[label_col] == i]
            n_i = len(subset)
            h_i = subset[hotspot_col].sum()
            er = (h_i / total_h) / (n_i / total_n) if total_h > 0 else 0
            results.append({'Cluster': labels[i], 'Hotspots': h_i, 'Area_Size': n_i, 'ER': round(er, 4)})
        return pd.DataFrame(results)

if __name__ == "__main__":
    # NAMA DATASET SESUAI PERMINTAAN
    file_path = 'DATASET_GITHUB_SUMATRA_Q3_2025.csv'

    if os.path.exists(file_path):
        df = pd.read_csv(file_path)
        model = VLIFModelSumatra()

        # Gunakan nama kolom asli dari dataset Anda
        df['FLFI_Generated'] = model.calculate_flfi(
            df['temperatur_rata_rata'],
            df['kelembapan_udara_rata_rata'],
            df['kelembapan_tanah'],
            df['status_lahan_gambut'],
            df['skor_risiko_tutupan_lahan']
        )

        # Jalankan Model
        df['Risk_Status'] = model.run_ufcm(df['FLFI_Generated'].values)

        # Tampilkan Hasil Validasi
        print("\n✅ VLIF-MODEL VALIDATION SUCCESSFUL")
        print("="*50)
        report = model.validate_er(df, 'Risk_Status', 'jumlah_hotspot')
        print(report.to_string(index=False))
    else:
        print(f"❌ File {file_path} tidak ditemukan di folder!")