# -*- coding: utf-8 -*-
"""Untitled32.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/143QiAYcef_QiGOvciuBnypi0T2HJmlD6
"""

import os
import sys
import numpy as np
import pandas as pd

# --- AUTO-INSTALLER ---
try:
    import geopandas as gpd
    import skfuzzy as fuzz
except ImportError:
    print("Installing geospatial libraries...")
    os.system(f"{sys.executable} -m pip install geopandas scikit-fuzzy matplotlib")
    import geopandas as gpd
    import skfuzzy as fuzz

import matplotlib.pyplot as plt
import matplotlib.patheffects as path_effects
import matplotlib.patches as mpatches
from matplotlib.colors import ListedColormap

# ==========================================
# 1. LOAD & RE-RUN MODEL (LOGIKA IBK/LVI)
# ==========================================
file_path = 'DATASET_GITHUB_SUMATRA_Q3_2025.csv'
path_geojson = 'gabungan_10_wilayah_batas_provinsi.geojson'

if not os.path.exists(file_path) or not os.path.exists(path_geojson):
    print("❌ Pastikan file CSV dan GeoJSON ada di folder yang sama!")
    sys.exit()

df = pd.read_csv(file_path)

# Logika Perhitungan FLFI (Sesuai main.py & Sintaks Asli)
es = 0.61078 * np.exp((17.27 * df['temperatur_rata_rata']) / (df['temperatur_rata_rata'] + 237.3))
vpd = es - (es * (df['kelembapan_udara_rata_rata'] / 100))
ibk_raw = df['kelembapan_tanah'] - ((df['status_lahan_gambut'] * 0.7) + (df['skor_risiko_tutupan_lahan'] * 0.3))
df['FLFI'] = (vpd + (1 - ibk_raw)) / 2

# U-FCM Clustering
X = df['FLFI'].values.reshape(1, -1)
cntr, u, _, _, _, _, _ = fuzz.cluster.cmeans(X, c=3, m=2, error=1e-5, maxiter=1000)
idx = np.argsort(cntr.flatten()) # 0:Aman, 1:Waspada, 2:Awas
df['cluster_id'] = np.argmax(u[idx], axis=0)

# ==========================================
# 2. HITUNG SKOR FLFRS PER PROVINSI (HASIL VALIDASI ANDA)
# ==========================================
# Masukkan nilai ER yang baru saja muncul di output main.py Anda:
ER_HIGH = 3.1493
ER_MOD  = 0.8657
ER_LOW  = 0.1694

def calculate_flfrs(x):
    total = len(x)
    p_high = (x == 2).sum() / total
    p_mod  = (x == 1).sum() / total
    p_low  = (x == 0).sum() / total
    # Rumus FLFRS (Persamaan 9 PDF)
    score = ((p_high * ER_HIGH) + (p_mod * ER_MOD) + (p_low * ER_LOW)) / ER_HIGH
    return score * 100 # Skala 0-100

stats = df.groupby('provinsi')['cluster_id'].agg(calculate_flfrs).reset_index()
stats.columns = ['provinsi', 'FLFRS']

# Penentuan Status Berdasarkan Threshold 25 & 50
def get_status_id(score):
    if score > 50: return 2   # AWAS
    if score >= 25: return 1  # WASPADA
    return 0                  # AMAN

stats['status_id'] = stats['FLFRS'].apply(get_status_id)

# ==========================================
# 3. GEOSPATIAL MAPPING
# ==========================================
gdf = gpd.read_file(path_geojson)
gdf['join_key'] = gdf['name'].str.upper().str.strip()
stats['join_key'] = stats['provinsi'].str.upper().str.strip()

merged = gdf.merge(stats, on='join_key', how='inner')

# Plotting
fig, ax = plt.subplots(1, 1, figsize=(15, 12), facecolor='white')
cmap = ListedColormap(['#2ecc71', '#f1c40f', '#e74c3c']) # Hijau, Kuning, Merah

merged.plot(column='status_id', ax=ax, cmap=cmap, edgecolor='black', linewidth=1.5, vmin=0, vmax=2)

# Labeling Nama Singkat & Skor FLFRS
short_names = {'SUMATERA UTARA': 'SUMUT', 'SUMATERA SELATAN': 'SUMSEL',
               'SUMATERA BARAT': 'SUMBAR', 'RIAU': 'RIAU', 'JAMBI': 'JAMBI',
               'ACEH': 'ACEH', 'BENGKULU': 'BENGKULU', 'LAMPUNG': 'LAMPUNG'}

for _, row in merged.iterrows():
    centroid = row['geometry'].centroid
    lbl = f"{short_names.get(row['join_key'], row['join_key'])}\n{row['FLFRS']:.1f}"
    txt = ax.text(centroid.x, centroid.y, lbl, fontsize=11, fontweight='black',
                  ha='center', va='center', color='black')
    txt.set_path_effects([path_effects.withStroke(linewidth=4, foreground='white')])

plt.title('SUMATRA FOREST AND LAND FIRE RISK MAP (Q3 2025)\nBASED ON FLF RISK SCORE (FLFRS) - SCALE 0-100',
          fontsize=16, fontweight='bold', pad=20)
ax.axis('off')

# Legenda Khusus
patches = [mpatches.Patch(color='#e74c3c', label='High Risk (FLFRS > 50)'),
           mpatches.Patch(color='#f1c40f', label='Moderate Risk (FLFRS 25-50)'),
           mpatches.Patch(color='#2ecc71', label='Low Risk (FLFRS < 25)')]
ax.legend(handles=patches, loc='lower right', title="Risk Status (Extraction Results)")

# Simpan Gambar
plt.savefig('RISK_MAP_FLFRS_FINAL.png', dpi=300, bbox_inches='tight')
plt.show()

print(f"✅ Peta berhasil dibuat: RISK_MAP_FLFRS_FINAL.png dengan ER High: {ER_HIGH}")